# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/OV7670_constraints.xdc

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ov7670_vga_0_0/design_1_ov7670_vga_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ov7670_vga_0_0 || ORIG_REF_NAME==design_1_ov7670_vga_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ov7670_controller_0_0/design_1_ov7670_controller_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ov7670_controller_0_0 || ORIG_REF_NAME==design_1_ov7670_controller_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ov7670_capture_0_0/design_1_ov7670_capture_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ov7670_capture_0_0 || ORIG_REF_NAME==design_1_ov7670_capture_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_debounce_0_0/design_1_debounce_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_debounce_0_0 || ORIG_REF_NAME==design_1_debounce_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_0 || ORIG_REF_NAME==design_1_clk_wiz_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_blk_mem_gen_0_0/design_1_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_blk_mem_gen_0_0 || ORIG_REF_NAME==design_1_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rgb444_to_gray_12bit_0_2/design_1_rgb444_to_gray_12bit_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_rgb444_to_gray_12bit_0_2 || ORIG_REF_NAME==design_1_rgb444_to_gray_12bit_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_debounce_0_1/design_1_debounce_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_debounce_0_1 || ORIG_REF_NAME==design_1_debounce_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_img_proc_top_0_0/design_1_img_proc_top_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_img_proc_top_0_0 || ORIG_REF_NAME==design_1_img_proc_top_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_mux_0_0/design_1_mux_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_mux_0_0 || ORIG_REF_NAME==design_1_mux_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ps2_top_0_0/design_1_ps2_top_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ps2_top_0_0 || ORIG_REF_NAME==design_1_ps2_top_0_0} -quiet] -quiet

# XDC: bd/design_1/design_1_ooc.xdc
